CREATE TABLE SBS_USUARIO
(
  USUARIOID NUMBER(10) NOT NULL,
  ROLID NUMBER(2) NOT NULL,
  CODIGOUSUARIO VARCHAR2(20) NOT NULL,
  CLAVESECRETA VARCHAR2(20) NOT NULL,
  EMAIL VARCHAR2(50) NOT NULL,
  APELLIDOPATERNO VARCHAR2(50) NOT NULL,
  APELLIDOMATERNO VARCHAR2(50) NOT NULL,
  PRIMERNOMBRE VARCHAR2(50) NOT NULL,
  SEGUNDONOMBRE VARCHAR2(50) NULL,
  ALIAS VARCHAR2(100) NULL,
  PRIMERAVEZLOGIN NUMBER(1) NULL,
  ACTIVO NUMBER(1) NOT NULL
)
;

ALTER TABLE SBS_USUARIO
ADD CONSTRAINT PK_USUARIOID
PRIMARY KEY(USUARIOID)
;

/*
CREATE PUBLIC SYNONYM SBS_USUARIO
FOR GMATOS.SBS_USUARIO;

DROP TABLE GMATOS.SBS_USUARIO;
DROP PUBLIC SYNONYM SBS_USUARIO FORCE;
*/
